import { randomBytes } from 'node:crypto'
import type { FastifyInstance } from 'fastify'
import type { IdentityServiceImpl } from '../identity-service.js'

interface SetupDeps {
  service: IdentityServiceImpl
  tokenStore:
    | {
        getUserId(tokenId: string): string | undefined
        setUserId(tokenId: string, userId: string): void
      }
    | undefined
}

/**
 * Short-lived in-memory link codes for multi-device account linking.
 *
 * These are intentionally not persisted: a restart invalidates all pending codes,
 * which is acceptable given the 5-minute TTL. Persistence would add complexity
 * (storage, migration) for minimal practical benefit.
 */
const linkCodes = new Map<string, { userId: string; expiresAt: number }>()

/**
 * Registers identity setup routes under the plugin's prefix (e.g. /api/v1/identity).
 *
 * POST /setup — first-time identity claim for API token holders.
 * POST /link-code — generate a one-time code to link a second device/token.
 */
export function registerSetupRoutes(app: FastifyInstance, deps: SetupDeps): void {
  const { service, tokenStore } = deps

  // POST /setup — claim an identity for the current JWT token.
  // On first call: creates a new user and links the token.
  // If linkCode is provided: links the token to an existing user instead.
  // Subsequent calls with the same token return the already-linked user.
  app.post('/setup', async (request, reply) => {
    const auth = (request as any).auth
    if (!auth?.tokenId) return reply.status(401).send({ error: 'JWT required' })

    // Idempotent: if this token is already linked, return the existing user
    const existingUserId = tokenStore?.getUserId?.(auth.tokenId)
    if (existingUserId) {
      const user = await service.getUser(existingUserId)
      if (user) return user
    }

    const body = request.body as any

    if (body?.linkCode) {
      // Link this token to an existing user account via a short-lived link code.
      // The code was generated by the existing token's /link-code endpoint.
      const entry = linkCodes.get(body.linkCode as string)
      if (!entry || entry.expiresAt < Date.now()) {
        return reply.status(401).send({ error: 'Invalid or expired link code' })
      }
      linkCodes.delete(body.linkCode as string)

      await service.createIdentity(entry.userId, {
        source: 'api',
        platformId: auth.tokenId as string,
      })

      tokenStore?.setUserId?.(auth.tokenId as string, entry.userId)
      return service.getUser(entry.userId)
    }

    // New user path — displayName is required
    if (!body?.displayName) return reply.status(400).send({ error: 'displayName is required' })

    const { user } = await service.createUserWithIdentity({
      displayName: body.displayName as string,
      username: body.username as string | undefined,
      source: 'api',
      platformId: auth.tokenId as string,
    })

    tokenStore?.setUserId?.(auth.tokenId as string, user.userId)
    return user
  })

  // POST /link-code — generate a one-time code so another token can link to this user.
  // The caller must already have a linked identity. Code expires in 5 minutes.
  app.post('/link-code', async (request, reply) => {
    const auth = (request as any).auth
    if (!auth?.tokenId) return reply.status(401).send({ error: 'JWT required' })

    const userId = tokenStore?.getUserId?.(auth.tokenId as string)
    if (!userId) return reply.status(403).send({ error: 'Identity not set up' })

    const code = randomBytes(16).toString('hex')
    const expiresAt = Date.now() + 5 * 60 * 1000

    // Evict stale codes before inserting to keep the map bounded
    for (const [k, v] of linkCodes) {
      if (v.expiresAt < Date.now()) linkCodes.delete(k)
    }

    linkCodes.set(code, { userId, expiresAt })
    return { linkCode: code, expiresAt: new Date(expiresAt).toISOString() }
  })
}
